### ISSUE TITLE
page reloads after Persona auto-login

### ISSUE THREAD

**Issue by almereyda** [fedwiki/wiki-client#101]
When my Persona tokens didn't expire yet, wiki logs me in gracefully.
Unfortunately I'm sometimes writing quicker than this happens, depending on the current connection, and I will end up with a nasty fork from localStorage, or even worse, losing my edits.

> Can't the client just *switch* internally to authorized mode? Why does it reload at all?

Maybe related to #92 .

**Comment by WardCunningham** [comment]
I'm going to assume that this and 92 have been corrected now that we avoid page reload after signin.
