### ISSUE TITLE
Unicode titles

### ISSUE THREAD

**Issue by egonelbre** [fedwiki/wiki-client#107]
The current scheme of simply removing non alphanumeric letters doesn't work for titles containing only non-ansi letters. For example `Öö` and `世界` would end up as the same slug. Similarly `@ sign` and `# sign`.

My current approach is this https://github.com/egonelbre/fedwiki/blob/master/slug.go#L36 and examples of how it behaves https://github.com/egonelbre/fedwiki/blob/master/slug_test.go#L9.

Essentially keep all unicode letters/numbers replace common symbols with their entity equivalents, except `-`, `,`, `.`, ` `, `_`, which are replaced by dashes. Also it's formatted such that there won't be double dashes or dashes around separator. Of course there's a problem, this scheme isn't backwards compatible.

Any thoughts regarding this issue? Probably it's been discussed before, but I didn't find the appropriate page.

**Comment by WardCunningham** [comment]
We are deeply interested in how the slug-creation process can be made more international without breaking any interoperability between existing servers and the client codes they serve.

Please join the discussion at #103.
