### ISSUE TITLE
Feature Request: [+] => create new page if needed

### ISSUE THREAD

**Issue by opn** [fedwiki/wiki-client#110]
This comes under the category of [[Riding Bicycle]] bugs. Even when familiar with the controls - I crash.

While on-a-role the most common mistake I make wile writing are the following:
* Click on page-link to creating a new page
* I'm thinking about what to write
* I click [+} to add a new paragraph
* Nothing happens
* I click on it again - nothing happens
* I realise I need to create the page first => fix the problem

The solution would be to automatically create a page from the ghost-page when I click on [+].

**Comment by WardCunningham** [comment]
The extra step makes more sense when you have templates to choose from. 
It also gives you a chance to see if you like the way the title looks.

**Comment by opn** [comment]
Was gong to say - true. But not so sure.

What is the intention when I click on [+]? My intention is not [Create a Page]. My intention is actually [Add a paragraph to that page I see before me while I am in writing flow]. The writing flow bit is important.

So OK - if I want to be safe - then the thing to do would be to throw up a dialogue / indication that allows me to hit return for the default template creation - and in this case an added factory.

When not in-writing-mode-flow - yes I take my time and look at a page, and decide which template, then create the page, then add appropriate content... but my intention when-in-writing-mode and therefore clicking on [+] is directly and simply to add-a-paragraph-and-not-care-about-templates. how do i know that I don't care about templates? Because if I did, I'd be thinking slower and wandering which sort of page to create - I'm not - i just want to type some more text - I'm in the flow :)

Scientifically - you'd resolve this by looking at users behaviour. how often do they click [+] and get confused (my guess is a lot) - and how often would they get annoyed that they created a page with the wrong template  if [+] created a page (rarely I suspect). If the latter was false - then we'd move to adding a safety dialogue?

How does that sound?

**Comment by WardCunningham** [comment]
I've looked into this issue along with other ghost page modifications. @opn is asking for an implicit 'create' before a factory 'add'. Wiki has some special handling of implicit 'fork' before edit. The latter is supported by bundling the fork into the add action and then separating them on the server. We've had good luck "discovering" functionality by keeping the interface close to the actual operations. Implicit fork hasn't had this good fortune and serves as a caution to not add this affordance. Sorry.
