### ISSUE TITLE
mixed content warnings on https due to some resource urls being hardcoded to http://

### ISSUE THREAD

**Issue by squiddle** [fedwiki/wiki-client#129]
I do not know if this has to be hardcoded or even why those are qualified urls at all.

The culprits are these two:

- https://github.com/fedwiki/wiki-client/blob/9c06fa385f9f6f587451bd19de4b2f1d92f6ca6f/lib/neighbors.coffee#L17
- https://github.com/fedwiki/wiki-client/blob/9c06fa385f9f6f587451bd19de4b2f1d92f6ca6f/lib/neighborhood.coffee#L24

**Comment by WardCunningham** [comment]
I agree, the protocol does seem superfluous, but the site substitution is required because both of these are fetching content from neighbors. What do you think it should say?

Ultimately we'd like to talk to more networks than the web so we should probably push the concept of a flag and sitemap into the server-facing abstraction layer once we have one.

**Comment by squiddle** [comment]
I see.

Having federated wiki on https also prevents to load federated pages from non https sources. So even if this would be fixed for one wiki instance, the problem of mixed content would come again. And this could probably only be fixed by having a proxy which is doing the fetch from the remote wiki. And this feels a bit inelegant. It could allow protocol adapters (e.g. for non http based sources which are not fetchable from a browser client), but this is probably later in the future.

**Comment by WardCunningham** [comment]
Yes, a proxy on the laptop could also hold access credentials should they be required. But a proxy on the wrong side of a firewall won't have the same visibilities interfering with our "fork to publish" convention.

Do you still see any value in removing the http: from the lines in question?

**Comment by squiddle** [comment]
oh right, the proxy has to be on the client.


> Do you still see any value in removing the http: from the lines in question?

Not really. in the end working federation is much more important to show the benefits of this style of wiki :)

I will close this for now.
