### ISSUE TITLE
wiki@next fails on collaborative link when unavailable site in journal

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki-client#189]
The site adapter trips up on a null xhr object when probing the journal for a missing page. To reproduce this error the search through the journal must encounter an unavailable site before finding the site with the desired page. Here is the test page and screen shots from the exception.

http://ward.asia.wiki.org/view/testing-slide-plugin

The problem is unrelated to the Slide plugin. I just happened to be working on it when I encountered the error. 

![screen shot 2017-04-22 at 4 57 57 pm](https://cloud.githubusercontent.com/assets/12127/25309295/5a565ef8-277e-11e7-9ecd-6f287d73810d.png)

Notice that localhost:3000 is unreachable and does not return an err status.

![screen shot 2017-04-22 at 4 57 10 pm](https://cloud.githubusercontent.com/assets/12127/25309298/67a4ba96-277e-11e7-8c56-218567ec4b3a.png)

This looks like an easy fix but I'm not setup to build wiki-client so I pass this along and continue working on the Slide plugin.

![screen shot 2017-04-22 at 4 54 58 pm](https://cloud.githubusercontent.com/assets/12127/25309303/8b6f5648-277e-11e7-9ba2-62bc8fd421a0.png)

Version details from the server in question.
```
root@asia:~# wiki -v
wiki: 0.11.0-2
wiki-server: 0.10.0-1
wiki-client: 0.9.0-2
wiki-security-friends: 0.1.0
wiki-security-passportjs: 0.1.2
wiki-plugin-activity: 0.3.0-0
wiki-plugin-audio: 0.1.5
wiki-plugin-bars: 0.3.0
wiki-plugin-bytebeat: 0.2.3
wiki-plugin-calculator: 0.2.2
wiki-plugin-calendar: 0.2.2
wiki-plugin-changes: 0.2.4
wiki-plugin-chart: 0.3.2
wiki-plugin-chess: 0.1.1
wiki-plugin-code: 0.2.2
wiki-plugin-cytodemo: 0.0.3
wiki-plugin-data: 0.2.2
wiki-plugin-factory: 0.2.4
wiki-plugin-favicon: 0.2.2
wiki-plugin-federatedwiki: 0.2.2
wiki-plugin-flagmatic: 0.1.3
wiki-plugin-force: 0.3.0
wiki-plugin-future: 0.2.2
wiki-plugin-graph: 0.0.2
wiki-plugin-grep: 0.1.5
wiki-plugin-html: 0.2.4
wiki-plugin-image: 0.2.2
wiki-plugin-json: 0.1.9
wiki-plugin-line: 0.3.0
wiki-plugin-map: 0.3.4
wiki-plugin-markdown: 0.2.6
wiki-plugin-mathjax: 0.2.3
wiki-plugin-metabolism: 0.2.2
wiki-plugin-method: 0.2.3
wiki-plugin-microtalk: 0.1.1
wiki-plugin-pagefold: 0.2.3
wiki-plugin-paragraph: 0.2.2
wiki-plugin-plugmatic: 1.1.0
wiki-plugin-pushpin: 0.3.0
wiki-plugin-radar: 0.3.0
wiki-plugin-reduce: 0.2.2
wiki-plugin-reference: 0.2.3
wiki-plugin-report: 0.2.2
wiki-plugin-rollup: 0.2.2
wiki-plugin-roster: 0.2.0-1
wiki-plugin-rostermatic: 1.0.9
wiki-plugin-scatter: 0.3.0
wiki-plugin-search: 0.1.1-1
wiki-plugin-slide: 0.1.1
wiki-plugin-tally: 0.1.4
wiki-plugin-transport: 0.1.2
wiki-plugin-video: 0.2.6
root@asia:~# 
```

**Comment by paul90** [comment]
Problem caused by site adapter not using the callback correctly - not return anything for `xhr.status`.

**Comment by WardCunningham** [comment]
Not the easy fix I was anticipating. Thanks for the quick turnaround.
