### ISSUE TITLE
Bug shift creating from an internal link

### ISSUE THREAD

**Issue by opn** [fedwiki/wiki-client#202]
When trying to create a new page by shift-clicking on an internal link for a page that does not exist the page title is named after the domain name of the site of origin instead of the page title in the Future Plugin:

<img width="996" alt="screenshot 2017-10-06 17 54 41" src="https://user-images.githubusercontent.com/80854/31289084-83ba62b6-aabf-11e7-8c4f-8c9abd080244.png">

**Comment by paul90** [comment]
Fixed in wiki-client@0.10.3
