### ISSUE TITLE
Focus and flicker issue caused by recent PRs

### ISSUE THREAD

**Issue by joshuabenuck** [fedwiki/wiki-client#233]
I have found two additional issues caused by my recent changes (#231 and #232).
1. It is impossible to get the Federation Search to retain focus. This has the same root cause as #232 and points to a flaw in how that was originally fixed.
2. There's a noticeable flicker when scrolling back through to previous pages. I suspect the call to focus in #231 is what is causing this, but haven't dug deep enough to prove it or think of a fix.

You can see both [here](https://server.wiki.randombits.xyz/view/welcome-visitors/view/federation-search/view/dns/view/hosting-options). Try clicking in the Federation Search box or using the arrow keys to scroll back to the page hidden on the left. The latter is easiest to see if you hit left and right a few times. Neither issue is present if I rollback my changes.

What is the best way for us to proceed here? I'm inclined to roll back the changes until all of these issues are fully understood, fully fixed, and the fixes have had some time to bake, but I'm also willing to continue to push forward from where we are now.

**Comment by paul90** [comment]
The flicker appears to be caused by focus getting set before the page scroll has completed. Fix in e7fb3fa88200e92479c1a773339f0f4f8fcad3f3 by setting the focus once the animation is complete.

**Comment by paul90** [comment]
The focus looks to be a bit more complicated. I think we will still want the click to propagate up to the page, so handle scrolling the page fully into view if the page is only partly displayed when the click in the input field is done. So, looks as if `$page.focus()` should only be called if the focus is not already within the page?

**Comment by paul90** [comment]
We can do that with `$page.focus() unless $.contains $page[0], $( document.activeElement ))`

**Comment by WardCunningham** [comment]
Well, I stumbled upon the Federation Search focus problem after upgrading my oldest Digital Ocean wiki farm. I showed up here to report the problem and noticed that you two were all over it. I'm assuming from comments here that pushing ahead is the best course? That's ok with me if you are on it.

I also noticed that the plugin supplied Federation Search does not meet our recommended utility page format so I will work on fixing that instead of worrying about focus. https://github.com/fedwiki/wiki-client/pull/229

**Comment by joshuabenuck** [comment]
I am unable to edit any items with these changes. Double clicking an item turns it to an editor briefly before changing back to the rendered content.

**Comment by paul90** [comment]
@joshuabenuck Is that with the changes in #234, I'm not seeing that problem which browser are you using?

**Comment by joshuabenuck** [comment]
@paul90 Yes, that is with the changes in #234. I'm using Chrome on macos.

**Comment by paul90** [comment]
Very strange.

**Comment by joshuabenuck** [comment]
There might be a better way to do this, but adding a clause that prevents focusing if we have an active editor seems to fix things.

This:
```coffeescript
   active.scrollContainer.animate({
    scrollLeft: scrollTarget
    }, () ->
      # only set focus if focus is not already within the page to get focus
      $page.focus() unless $.contains $page[0], $( document.activeElement ))
```

becomes this:
```coffeescript
   active.scrollContainer.animate({
    scrollLeft: scrollTarget
    }, () ->
      # don't set focus if focus is already within the page to get focus
      return if $.contains $page[0], $( document.activeElement )
      # or there is an active editor
      return if $(".textEditing").length != 0
      $page.focus()
```

I verified that pages still scroll fully into view and I'm able to edit items.

Unfortunately, I still see an issue where clicking in the federation search box loses focus soon after it receives it.

**Comment by paul90** [comment]
As a short term expedient I have re-published client version 0.15.0 as 0.15.3 - so the current release does not contain the focus changes. This will allow time to resolve what is happening...

The one strange thing I do notice is that using the keyboard to move the cursor within the search box as well as moving the cursor also scrolls the lineup. So, keyboard events are bubbling up from there, and I expect any other html input field.

**Comment by joshuabenuck** [comment]
This is all starting to make sense to me.

@paul90, I don't think your unless clause ever returns true. If I change it from:
```coffeescript
$page.focus() unless $.contains $page[0], $( document.activeElement )
```

to:
```coffeescript
$page.focus() unless $.contains $page[0], document.activeElement
```
I not only don't need my additional clause to be able to edit changes, the federation search text box now retains its focus when clicked. The call to stopPropagation from PR #232 can also be removed will no ill effect.

The strange thing you mentioned was actually there in a less noticeable form before my changes. Prior to pages being able to receive keyboard focus the drop shadow would still change if left or right was pressed, but the keyboard focus would stay on the text input. Once they became able to receive focus, pressing left or right causes the text input to immediately lose focus.

This can be corrected by adding a keydown handler to search.coffee in the search plugin which merely stops the propagation of the left and right keydown events.

```coffeescript
  keydown = (e) ->
    # Don't allow left or right to bubble up.
    if e.keyCode == 37 or e.keyCode == 39
      e.stopPropagation()

  handle = (request) ->
    if request.input
      $item.request = request
      $item
        .find('span')
        .append '<input type=text style="width: 95%;"></input>'
        .keyup(keystroke)
        .keydown(keydown)
```

I can create a pull request to the wiki-plugin-search repo in the morning if you don't beat me to it.

I think the small change to your PR plus the proposed change to the search plugin will fix the known issues we have discovered.

**Comment by paul90** [comment]
It won't just be the text input in the search plugin, but also in any other plugin. The only other one I can currently think of is the html plugin.

**Comment by joshuabenuck** [comment]
Good point.

It looks like we already handle the case of textareas. We could modify the guard clause in legacy.coffee's keydown handler.

From this
```coffeescript
if direction && not (event.target.tagName is "TEXTAREA")
```
to this
```coffeescript
if direction && not $(event.target).is(":input")
```
:input [handles](https://api.jquery.com/input-selector/) "all input, textarea, select, and button elements". It does not handle contentEditable divs, but I'd rather handle that when we run into it.

This would be cleaner than requiring all plugins to add an extra key down handler. Two other options we could explore are adding more delegates to legacy.coffee (ick) or registering the extra key handlers somewhere in the plugin API (feels more complex than just modifying the legacy's key down handler).

**Comment by paul90** [comment]
using `:input` in legacy sounds good

**Comment by paul90** [comment]
#234 currently has change to legacy's keydown handler, as far as I can see it behaves correctly.
