### ISSUE TITLE
“Find pages with links to this title” on localhost always returns zero

### ISSUE THREAD

**Issue by rybesh** [fedwiki/wiki-client#242]
I am running an instance of fedwiki on localhost for my personal use. When I open up the search from a page, and click on the button under “Find pages with links to this title” (SEARCH LINKS), I always get zero results, even when I know I have links to that page.

Does “search links” only work for public wikis?

**Comment by almereyda** [comment]
Yes, search is a service that only crawls the publicly visible federation. You can read more about it on:

- http://search.fed.wiki.org/federation-search.html
- http://search.fed.wiki.org:3030/

**Comment by WardCunningham** [comment]
We are interested in developing a distributed crawl that could be bundled with the wiki server and operate behind firewalls. This raises questions of security and resource allocation that can be solved but have prevented progress on this ambition to date.
