### ISSUE TITLE
Hamburger menu items have flags that go nowhere.

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki-client#260]
The Hamburger button creates a ghost page of Reference plugins who's link label brings up a useful page from within a plugin's About pages. It does not bring up the entry About page for the plugin but it could. Right now clicking the Reference's flag goes nowhere. Maybe this should bring up the entry About page?

![image](https://user-images.githubusercontent.com/12127/72954334-d8a93c80-3d4c-11ea-9f97-8c3517cae41b.png)

Some plugins offer a variety of interesting pages that can all be found from the entry About page. Rather than redundantly list all of these in the hamburger menu, let's just link the flag to the entry About page so that the full repertoire of services become available.

This would be a small deviation from what one usually expects of the flag behavior but it is already different and useless too.

The Reference plugin might not be configurable enough right now to encode this behavior. If not we can always supplement the Item json with enough clues to enable the desired rendering into html.

**Comment by WardCunningham** [comment]
Here is where the hamburger button constructs the Item json with fields, title, slug, type and text.

https://github.com/fedwiki/wiki-client/blob/3fcd57c26e968063bf10306b52de8f7dbf5782fc/lib/legacy.coffee#L307-L310

**Comment by WardCunningham** [comment]
Here is where the Reference plugin (part of wiki-client) translates these parameters into html.

https://github.com/fedwiki/wiki-client/blob/3fcd57c26e968063bf10306b52de8f7dbf5782fc/lib/reference.coffee#L19-L29

**Comment by paul90** [comment]
Has been fixed at some point
