### ISSUE TITLE
The search-index span highlighting shouldn't match partial words.

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki-client#261]
When I search for "time" I shouldn't see those letters highlighted in the middle of another word as it is in the word "sometimes" in this example:

![image](https://user-images.githubusercontent.com/12127/74092666-1233b480-4a7c-11ea-9347-38bd126bc37d.png)

I'm guessing that the regex word-break (\b) could be used to prevent this. For example, this line, and the similar regex below it,

https://github.com/fedwiki/wiki-client/blob/20ef500aa9b400216b1e7e8a79cab66dd4cf488b/lib/search.coffee#L94

could construct the regex as `new RegExp("\b(#{escapeRegExp(searchQuery)})\b"`.

**Comment by paul90** [comment]
As the search might only be searching for a partial word `"\b(#{escapeRegExp(searchQuery)})"` would be better.

**Comment by WardCunningham** [comment]
So "time" and "times" should match but not "sometimes".

Sounds right to me.

**Comment by paul90** [comment]
This was fixed at some point, I think when we switched to using minisearch
