### ISSUE TITLE
Page Too Large? 

### ISSUE THREAD

**Issue by cliveb** [fedwiki/wiki-client#272]
Frank and I are wondering if I have found the limit for a wiki JSON page? The page frame turned yellow when we tried to fork it. Is page too large is to fork?

[](http://clive.tries.fed.wiki/view/page-too-large)

I removed embedded videos which seemed to help. 

I started looking at page console error with Google browser tools inspector and found CORS and errors and plugin errors. Any ideas if the limit has been reached?

[](http://clive.tries.fed.wiki/view/tracking-down-covid-19-origin)

jquery-migrate-1.4.1.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
client.max.js:4 Window Name: clive.tries.fed.wiki
client.max.js:5257 siteAdapter: loading data
client.max.js:5444 wiki.origin.get system/factories.json
client.max.js:3680 loading url: /security/security.js
client.max.js:5394 wiki.local.get recent-changes.json
client.max.js:3291 (2) [{…}, null]
client.max.js:5444 wiki.origin.get recent-changes.json
client.max.js:5408 tried to local fetch a page that isn't local
client.max.js:3680 loading url: /security/modernizr-custom.js
client.max.js:3340 got view {title: "Recent Changes", story: Array(2), journal: Array(14)}
client.max.js:4564 .page keys  (2) ["d3ec8ae6", undefined]
client.max.js:4576 lineup keys ["d3ec8ae6"]
client.max.js:5590 creating temp flag for ward.bay.wiki.org
2client.max.js:2709 neighbor - flag
client.max.js:3712 notifIndex 0 about to render (2) [div.item.paragraph.ui-sortable-handle, div.item.activity.ui-sortable-handle]
client.max.js:3680 loading url: /plugins/activity/activity.js
VM309:219 modernizr loaded
client.max.js:3680 loading url: /security/winchan.js
client.max.js:5350 findAdapter:  ward.bay.wiki.org //ward.bay.wiki.org
client.max.js:5638 Prefix for ward.bay.wiki.org is //ward.bay.wiki.org
client.max.js:5350 findAdapter:  ward.bay.wiki.org //ward.bay.wiki.org
client.max.js:5711 Prefix for ward.bay.wiki.org is //ward.bay.wiki.org, about to fixup links
client.max.js:5274 siteAdapter: withCredentials data loaded
client.max.js:5394 wiki.local.get tracking-down-covid-19-origin.json
client.max.js:3291 (2) [{…}, null]
client.max.js:5444 wiki.origin.get tracking-down-covid-19-origin.json
client.max.js:5408 tried to local fetch a page that isn't local
client.max.js:5444 wiki.origin.get system/sitemap.json
client.max.js:5469 wiki.origin.get system/site-index.json
client.max.js:5264 siteAdapter: data loaded
tracking-down-covid-19-origin:1 Access to XMLHttpRequest at 'http://ward.bay.wiki.org/system/site-index.json' from origin 'http://clive.tries.fed.wiki' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
client.max.js:2331 error loading index ward.bay.wiki.org {msg: "", xhr: {…}}
jquery-2.2.4.min.js:4 GET http://ward.bay.wiki.org/system/site-index.json net::ERR_FAILED
send @ jquery-2.2.4.min.js:4
ajax @ jquery-2.2.4.min.js:4
u @ client.max.js:5835
getIndex @ client.max.js:5890
n @ client.max.js:2317
setTimeout (async)
c @ client.max.js:2342
a.registerNeighbor @ client.max.js:2364
s @ client.max.js:4784
(anonymous) @ client.max.js:3346
n @ client.max.js:5440
success @ client.max.js:5450
i @ jquery-2.2.4.min.js:2
fireWith @ jquery-2.2.4.min.js:2
z @ jquery-2.2.4.min.js:4
(anonymous) @ jquery-2.2.4.min.js:4
load (async)
send @ jquery-2.2.4.min.js:4
ajax @ jquery-2.2.4.min.js:4
get @ client.max.js:5445
(anonymous) @ client.max.js:3294
n @ client.max.js:5390
get @ client.max.js:5407
get @ client.max.js:3290
h @ client.max.js:3336
l.get @ client.max.js:3394
(anonymous) @ client.max.js:4790
p @ client.max.js:4747
e @ client.max.js:1928
(anonymous) @ client.max.js:1923
i @ jquery-2.2.4.min.js:2
fireWith @ jquery-2.2.4.min.js:2
ready @ jquery-2.2.4.min.js:2
J @ jquery-2.2.4.min.js:2
client.max.js:2325 clive.tries.fed.wiki index loaded
client.max.js:3340 got view {title: "Tracking Down Covid-19 Origin", story: Array(203), journal: Array(2881)}
client.max.js:4564 .page keys  (2) ["d3ec8ae6", "c211e6a2"]
client.max.js:4576 lineup keys (2) ["d3ec8ae6", "c211e6a2"]
client.max.js:3712 notifIndex 2 about to render (203) [div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.audio.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.image.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, div.item.pagefold.ui-sortable-handle, div.item.markdown.ui-sortable-handle, …]
client.max.js:3680 loading url: /plugins/markdown/markdown.js
client.max.js:3680 loading url: /plugins/pagefold/pagefold.js
client.max.js:3680 loading url: /plugins/audio/audio.js
DevTools failed to load source map: Could not load content for http://clive.tries.fed.wiki/view/recent-changes/view/pagefold.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://clive.tries.fed.wiki/view/recent-changes/view/audio.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by paul90** [comment]
Looking at the browser's developer tools network panel I see the page has grown to 5.07MB, of this the journal is taking something like 97% of the space.

**Comment by WardCunningham** [comment]
I can log on to the server and remove some duplication. Remind me exactly which page is causing trouble.

**Comment by WardCunningham** [comment]
if the page has many sections, one good strategy would be to make a new page for each section and drag the content there. Then you could fork a much smaller revision of the original page and make that summarize the new pages. By this process you would lose the very history that I offered to delete and be left in a better overall configuration than my hacking can provide.

**Comment by cliveb** [comment]
"if the page has many sections"

Is there anyway to grant authority to loose unwanted history on a page from the client without server admin?

Perhaps a 'fork and clean' where the history is dropped off. 

I have two pages that load very slowly: 
http://clive.tries.fed.wiki/view/tracking-down-covid-19-origin
http://clive.tries.fed.wiki/view/deep-thoughts-on-wiki
  
This would go quite a ways toward a solution for the 'right-to-be-forgotten' on pages you have on your account (came up Tues with Timur from Russia in dev/user chat). Provide a non technical solution to page too large?

**Comment by paul90** [comment]
To answer your opening question, the wiki server limits the size of any upload. This is currently set to 5Mb by default.

Pages can grow beyond that size, as an edit only sends the details of the edit to the server (the edit is effectively performed on both the client and server).

Once the page has grown too big, any fork action will fail as it tries to send the entire page to the server. When the action fails the page will get saved locally, hence the yellow border.

I'm currently writing a script, as time allows, that will compress the journal by only only keeping a single journal entry of actions on any page item that happen within a time period. For the 'tracking down covid 19 origin' page this is currently reducing the number of journal entries from 2881 to 1577.

**Comment by cliveb** [comment]
Terrific. I expect authors who make many edits, and their server admins, will appreciate how useful.

**Comment by paul90** [comment]
This was addressed, at least in part, with the introduction of the journalmatic plugin which contains a script to compress a page's journal.
