### ISSUE TITLE
Can't drop page from local storage, needs more logic in lib/drop.coffee

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki-client#61]
The drop handling logic in lib/drop.coffee doesn't understand when the page dropped has a copy in browser local storage. If the drop logic replaced 'local' with the remote origin then (somehow) the CORS properties of the remote site permit retrieving the desired page from local storage even than in the drop context the local storage is indexed under the remote site.

Mike Caulfield identified this problem in email that I have partially transcribed:
http://ward.fed.wiki.org/view/wants-and-needs/view/lost-my-origin

**Comment by paul90** [comment]
A recent change to the [changes plugin](/fedwiki/wiki-plugin-changes/pull/7) gives the option to export pages that have been saved to local storage. While not a solution to drag & drop of these pages it provides an alternative way of achieving the same result.
