### ISSUE TITLE
Persona Causes Infinite Refresh Loop

### ISSUE THREAD

**Issue by hallahan** [fedwiki/wiki-client#92]
Sometimes this happens, sometimes it does not. But, if you go to http://wiki.theoutpost.io you will find that the browser keeps refreshing and it is repeatedly signing in and out of Persona. Can anyone reproduce this?

**Comment by hallahan** [comment]
Here is a video of the bug in action:

https://www.youtube.com/watch?v=4tfZA5hBJh4&feature=youtu.be

**Comment by paul90** [comment]
Don't suppose there is anything informative in the browser console?

If you can it would probably also help if you can also look at the expiry dates on the following cookies `browserid_state` on login.persona.org, and `session` on your wiki site. I have a vague recollection there were some thoughts about session state getting out of step, but that was a long time ago...

**Comment by hallahan** [comment]
I'm noticing there is a pending GET request coming from an iframe. When the page goes in its repeated request seizure, I see this request is what is pending each time.

![screenshot 2015-02-08 09 41 50](https://cloud.githubusercontent.com/assets/556367/6097569/c2764650-af77-11e4-9d9f-8945a574c405.png)
 
```
Request URL:https://login.persona.org/wsapi/address_info?email=nick%40theoutpost.io&issuer=default
```

Note: this problem seems to happen for a minute or 2, and then things calm down and the site functions normally - strange.

Looking at requests to the main server, the Expires / Max-Age values of requests is "N/A".

We have the same thing for `browserid_state` as well.

**Comment by WardCunningham** [comment]
I'm going to assume that this and 101 have been corrected now that we avoid page reload after signin.
