### ISSUE TITLE
license....

### ISSUE THREAD

**Issue by pombredanne** [fedwiki/wiki-client#95]
You state in the package.json this fine piece of code (and several related repos ) is MIT-licensed.
Please add the license text.... make it easy for others to consume/reuse your code ;)

**Comment by WardCunningham** [comment]
You could help me do as you wish if you could pull request the change you desire with a pointer to documentation that helps me understand what you are suggesting. I'm sure the package.json expectations you assume are documented somewhere.

If you're having trouble with corporate lawyers, I'm happy to join a conference call so long as the vp of engineering and the lawyers involved join the call.

**Comment by pombredanne** [comment]
@WardCunningham let me do that pull request.
You package.json says this is MIT license. this is a fairly simple license that has essentially a single requirement: keep a copy of the license with the code. If that license is not provided by the project, you make it a tad harder to comply ... 
what should be the copyright you want on your MIT license?
Something like?
Copyrifght (c) 2015 Ward Cunnigham and the fedwiki contributors

Then you can use this template alright 
http://mit-license.org/

**Comment by pombredanne** [comment]
For reference this is the only mention of your license in this repo:
https://github.com/fedwiki/wiki-client/blob/master/package.json#L46
(there are of course many other licenses of third-party components but that is another story altogether)

**Comment by WardCunningham** [comment]
The concerns in this issue have been addressed by #99. Many thanks to @paul90 for creating and managing these repos and now documenting the intellectual property within them.
